---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sovannlyna-nextjs-deployment-16f63861                  # Ingress name
  labels:
    app: sovannlyna-nextjs-deployment-16f63861
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "sovannlyna-nextjs-deployment-16f63861.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sovannlyna-nextjs-deployment-16f63861               # Links to Service name dynamically
                port:
                  number: 3000  # Links to service port dynamically
